# Generated by Django 5.1.1 on 2025-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/categories/formal_shirt.jpg', upload_to='uploads/categories'),
        ),
    ]
